// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALczGhqgvLnri8y2CwpE6cQ20kbWEXsu0',
    appId: '1:582376843986:web:569b79cd4e048551a49b0b',
    messagingSenderId: '582376843986',
    projectId: 'bloc-final-example',
    authDomain: 'bloc-final-example.firebaseapp.com',
    storageBucket: 'bloc-final-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0D6RL_jnkbtyMwL05T0cECVSCbUrUjbw',
    appId: '1:582376843986:android:56b67505b4f0efd7a49b0b',
    messagingSenderId: '582376843986',
    projectId: 'bloc-final-example',
    storageBucket: 'bloc-final-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjis9Ud2Pc8Y-w7ao-uH9yhMuHGIujHBM',
    appId: '1:582376843986:ios:e37825f11e3ae784a49b0b',
    messagingSenderId: '582376843986',
    projectId: 'bloc-final-example',
    storageBucket: 'bloc-final-example.appspot.com',
    iosClientId: '582376843986-vf8sqsgfngvbbkmc4kkh034oi9fqmsci.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalBlocExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjis9Ud2Pc8Y-w7ao-uH9yhMuHGIujHBM',
    appId: '1:582376843986:ios:e37825f11e3ae784a49b0b',
    messagingSenderId: '582376843986',
    projectId: 'bloc-final-example',
    storageBucket: 'bloc-final-example.appspot.com',
    iosClientId: '582376843986-vf8sqsgfngvbbkmc4kkh034oi9fqmsci.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalBlocExample',
  );
}
